#!/usr/bin/env bash

set -e

function build {
  (
    cd src/gmp-6.2.1
    make distclean
    ./configure --host=arm-none-eabi --disable-assembly CFLAGS="$2"
    make -j $(nproc)
    cp .libs/libgmp.a ../lib/
    cp gmp.h ../include/gmp.h
  )

  (
    cd src/mpfr-4.1.0
    # We need to configure the Makefile to can clean the build directory before building
    ./configure --with-gmp=../ --host=arm-none-eabi --disable-shared CFLAGS="$2"
    # Autoreconf is required, becaise the version may have changed
    autoreconf
    make distclean
    # Now, we need to reconfigure the Makefile, because the distclean command above removed the Makefile
    ./configure --with-gmp=../ --host=arm-none-eabi --disable-shared CFLAGS="$2"
    autoreconf
    # Now, we can build the library
    make -j $(nproc)
    # Copy the library to the correct location
    cp src/.libs/libmpfr.a ../lib/
    # Copy the header files to the correct location
    cp src/mpfr.h ../include/mpfr.h
  )

  (
    cd src/mpfi-1.5.4
    make distclean
    autoreconf
    # Quick and dirty hack for github pages to work
    # Setup symlinks manually
    mkdir -p build-aux
    mkdir -p m4
    
    ln -sf /usr/share/libtool/build-aux/ltmain.sh    build-aux/ltmain.sh
    ln -sf /usr/share/automake-1.16/missing          build-aux/missing
    ln -sf /usr/share/automake-1.16/config.sub       build-aux/config.sub
    ln -sf /usr/share/automake-1.16/compile          build-aux/compile
    ln -sf /usr/share/automake-1.16/config.guess     build-aux/config.guess
    ln -sf /usr/share/automake-1.16/test-driver      build-aux/test-driver
    ln -sf /usr/share/automake-1.16/install-sh       build-aux/install-sh
    ln -sf /usr/share/automake-1.16/ar-lib           build-aux/ar-lib
    ln -sf /usr/share/automake-1.16/depcomp          build-aux/depcomp
    ln -sf /usr/share/aclocal/ltoptions.m4           m4/ltoptions.m4
    ln -sf /usr/share/aclocal/ltsugar.m4             m4/ltsugar.m4
    ln -sf /usr/share/aclocal/libtool.m4             m4/libtool.m4
    ln -sf /usr/share/aclocal/lt~obsolete.m4         m4/lt~obsolete.m4
    ln -sf /usr/share/aclocal/ltversion.m4           m4/ltversion.m4
    
    
    ./configure --with-mpfr=$(pwd)/../ --with-gmp=$(pwd)/../ --host=arm-none-eabi CFLAGS="$2"
    # Remove aclocal.m4, because it will create conflicts with the system version
    rm aclocal.m4
    # Reconfigure the project, to recreate aclocal.m4
    autoreconf
    # Build the library
    make -j $(nproc)
    # Copy the library to the correct location
    cp src/.libs/libmpfi.a ../lib/
    # Copy the header files to the correct location
    cp src/mpfi.h ../include/mpfi.h
    
    #rm -r build-aux
    #rm -r m4
  )
  
  (
    cd src/micropython-1.12/numworks
    make clean
    # We need to use a script to build MicroPython, because the make command crashes in MicroPython because it tries to link without the required libraries
    ./mklib
  )
}

echo "buildDeps is deprecated. Use Makefile instead."
exit 1

# build n0100 "-Os -fdata-sections -ffunction-sections -DNDEBUG -mthumb -march=armv7e-m -mfloat-abi=hard -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -fno-strict-aliasing --specs=nosys.specs"
build n0110 "-Os -fdata-sections -ffunction-sections -DNDEBUG -mthumb -march=armv7e-m -mfloat-abi=hard -mcpu=cortex-m7 -mfpu=fpv5-sp-d16 -fno-strict-aliasing --specs=nosys.specs"
